/**
 * Type definitions
 */
import { ICharacteristicMap } from '../types'

export default <ICharacteristicMap>{
  wheelchair: [
    'maxSlope',
    'passageLength',
    'passageWidth',
    'stepHeight',
    'tableHeight',
    'reachHeight',
    'bedHeight',
    'bedAdjacentSpace',
    'wcAdjacentDistance',
    'wcFrontDistance',
    'wcSeatHeight',
    'wcFixedHandrail',
    'wcFoldableHandrail',
    'eurokey',
    'wcSinkDistance',
    'hygieneNeeds',
    'showerFixedHandrail',
    'showerFoldableHandrail',
    'bathSeat',
  ],
  electricWheelchair: [
    'maxSlope',
    'passageLength',
    'passageWidth',
    'stepHeight',
    'tableHeight',
    'reachHeight',
    'bedHeight',
    'bedAdjacentSpace',
    'wcAdjacentDistance',
    'wcFrontDistance',
    'wcSeatHeight',
    'wcFixedHandrail',
    'wcFoldableHandrail',
    'eurokey',
    'wcSinkDistance',
    'hygieneNeeds',
    'showerFixedHandrail',
    'showerFoldableHandrail',
    'bathSeat',
  ],
  cane: [
    'maxSlope',
    'handrail',
    'wcFixedHandrail',
    'wcFoldableHandrail',
    'eurokey',
    'wcSinkDistance',
    'hygieneNeeds',
    'showerFixedHandrail',
    'showerFoldableHandrail',
    'bathSeat',
  ],
  scooter: [
    'maxSlope',
    'passageLength',
    'passageWidth',
    'stepHeight',
    'tableHeight',
    'reachHeight',
    'bedHeight',
    'bedAdjacentSpace',
    'wcAdjacentDistance',
    'wcFrontDistance',
    'wcSeatHeight',
    'wcFixedHandrail',
    'wcFoldableHandrail',
    'eurokey',
    'wcSinkDistance',
    'hygieneNeeds',
    'showerFixedHandrail',
    'showerFoldableHandrail',
    'bathSeat',
  ],
}
