export default [
  { id: 1, label: 'Grisons', activities: [1, 2, 3, 4, 5, 6, 7, 8] },
  { id: 2, label: 'Suisse orientiale', activities: [2, 4, 5] },
  { id: 3, label: 'Région zurichoise', activities: [1, 2, 3] },
  { id: 4, label: 'Lucerne / Lac des Quatre-Cantons', activities: [4, 6, 8] },
  { id: 5, label: 'Région bâloise', activities: [6, 7, 8] },
  { id: 6, label: 'Région Berne', activities: [1, 2, 3, 4, 5] },
  { id: 7, label: 'Jura & Trois-Lacs', activities: [] },
  { id: 8, label: 'Vaud', activities: [2, 3, 4, 5, 6] },
  { id: 9, label: 'Genève', activities: [1, 8] },
  { id: 10, label: 'Valaise', activities: [2, 7] },
  { id: 11, label: 'Tessin', activities: [3, 4] },
  { id: 12, label: 'Région Fribourg', activities: [6, 7] },
  { id: 13, label: 'Région Argovie et Soleure', activities: [1, 3, 5, 8] },
]
