export default [
  { id: 1, key: 'grisons', activities: [1, 2, 3, 4, 5, 6, 7, 8] },
  { id: 2, key: 'orientiale', activities: [2, 4, 5] },
  { id: 3, key: 'zurich', activities: [1, 2, 3] },
  { id: 4, key: 'lucerne', activities: [4, 6, 8] },
  { id: 5, key: 'bale', activities: [6, 7, 8] },
  { id: 6, key: 'berne', activities: [1, 2, 3, 4, 5] },
  { id: 7, key: 'jura', activities: [] },
  { id: 8, key: 'leman', activities: [2, 3, 4, 5, 6] },
  { id: 9, key: 'geneve', activities: [1, 8] },
  { id: 10, key: 'valais', activities: [2, 7] },
  { id: 11, key: 'tessin', activities: [3, 4] },
  { id: 12, key: 'fribourg', activities: [6, 7] },
  { id: 13, key: 'argovie', activities: [1, 3, 5, 8] },
  { id: 14, key: 'lichtenstein', activities: [1, 3, 5, 8] },
]
